input {
  file {
    path => "/usr/share/logstash/app-logs/lifepulse.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  date { match => ["timestamp", "ISO8601"] target => "@timestamp" }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "lifepulse-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
